name: project_prm393
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/LogoKing.png
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoKing.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/LogoKing.png"