// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GsFrBQmNMSm7zZHC-uUPQrbLPtN22Pk',
    appId: '1:690508403495:web:010e69435157496a5dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    authDomain: 'legoking-vua3618.firebaseapp.com',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    measurementId: 'G-MDBLV57GMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pqZ48R7Zo3W7cZa1M8TcECOxCSgMndo',
    appId: '1:690508403495:android:e2c86cb6d91cabec5dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDif_BaKuhmHCe9Dr8ay-aXwsghOurE2qk',
    appId: '1:690508403495:ios:ef2f30ee7f6e1dc95dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    iosBundleId: 'com.example.projectPrm393',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDif_BaKuhmHCe9Dr8ay-aXwsghOurE2qk',
    appId: '1:690508403495:ios:ef2f30ee7f6e1dc95dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    iosBundleId: 'com.example.projectPrm393',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4GsFrBQmNMSm7zZHC-uUPQrbLPtN22Pk',
    appId: '1:690508403495:web:075ffb6201af38655dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    authDomain: 'legoking-vua3618.firebaseapp.com',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    measurementId: 'G-QF8Q1Z2BVS',
  );
}
