// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GsFrBQmNMSm7zZHC-uUPQrbLPtN22Pk',
    appId: '1:690508403495:web:010e69435157496a5dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    authDomain: 'legoking-vua3618.firebaseapp.com',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    measurementId: 'G-MDBLV57GMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pqZ48R7Zo3W7cZa1M8TcECOxCSgMndo',
    appId: '1:690508403495:android:4cca5357e9ed2fa75dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDif_BaKuhmHCe9Dr8ay-aXwsghOurE2qk',
    appId: '1:690508403495:ios:22379468235f4ded5dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDif_BaKuhmHCe9Dr8ay-aXwsghOurE2qk',
    appId: '1:690508403495:ios:22379468235f4ded5dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4GsFrBQmNMSm7zZHC-uUPQrbLPtN22Pk',
    appId: '1:690508403495:web:2f5b4ca48151a9ab5dcf02',
    messagingSenderId: '690508403495',
    projectId: 'legoking-vua3618',
    authDomain: 'legoking-vua3618.firebaseapp.com',
    storageBucket: 'legoking-vua3618.firebasestorage.app',
    measurementId: 'G-HE4SK22PH2',
  );
}
